#!/usr/bin/env node
/**
 * copy-abi — copies contract ABIs (and the localhost deployment addresses)
 * from `contracts/` into `web/src/abi/` as generated TypeScript modules.
 *
 * Ownership: never import across packages. The generated files are build
 * artifacts (`src/abi/` is gitignored); this script runs before dev, build,
 * lint, typecheck and tests so a fresh checkout always has them.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contractsDir = join(root, '..', 'contracts');
const outDir = join(root, 'src', 'abi');

const header = `/** Generated by \`npm run abi\` — do not edit by hand. */\n`;

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function writeAbi(contractName, outName) {
  const artifact = readJson(join(contractsDir, 'abi', `${contractName}.json`));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`${contractName}.json has no top-level "abi" array`);
  }
  writeFileSync(
    join(outDir, `${outName}.ts`),
    `${header}export const ${outName} = ${JSON.stringify(artifact.abi)} as const;\n`
  );
  console.log(`abi: ${contractName} -> src/abi/${outName}.ts (${artifact.abi.length} entries)`);
}

function writeDeployments() {
  const deployment = readJson(join(contractsDir, 'deployments', 'localhost.json'));
  for (const key of ['ECIMultiSig', 'ElectionManager', 'Semaphore']) {
    if (typeof deployment[key] !== 'string' || !deployment[key].startsWith('0x')) {
      throw new Error(`localhost.json is missing a valid ${key} address`);
    }
  }
  writeFileSync(
    join(outDir, 'deployments.ts'),
    `${header}export const localhostDeployment = ${JSON.stringify(
      {
        ECIMultiSig: deployment.ECIMultiSig,
        ElectionManager: deployment.ElectionManager,
        Semaphore: deployment.Semaphore,
        chainId: deployment.chainId
      },
      null,
      2
    )} as const;\n`
  );
  console.log('abi: localhost deployment addresses -> src/abi/deployments.ts');
}

mkdirSync(outDir, { recursive: true });
writeAbi('ECIMultiSig', 'ecimultisig');
writeAbi('ElectionManager', 'electionManager');
writeDeployments();
